"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";

type Props={workspaceCode:string;token:string};
const masks=[
 {id:"s300-alfa",name:"S-300 Alfa",url:"/data/defensa-s300/s300_alfa.geojson"},
 {id:"s300-bravo",name:"S-300 Bravo",url:"/data/defensa-s300/s300_bravo.geojson"},
 {id:"s300-charly",name:"S-300 Charly",url:"/data/defensa-s300/s300_charly.geojson"},
 {id:"s300-delta",name:"S-300 Delta",url:"/data/defensa-s300/s300_delta.geojson"},
];
export default function ThreeDMap({workspaceCode,token}:Props){
 const ref=useRef<HTMLDivElement|null>(null); const mapRef=useRef<maplibregl.Map|null>(null); const [visible,setVisible]=useState<Record<string,boolean>>(Object.fromEntries(masks.map(m=>[m.id,true]))); const [exaggeration,setExaggeration]=useState(1.5); const [status,setStatus]=useState("Inicializando terreno 3D...");
 useEffect(()=>{if(!ref.current||mapRef.current)return; const map=new maplibregl.Map({container:ref.current,center:[-66.5,-27.5],zoom:5.4,pitch:62,bearing:-18,style:{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap"},terrain:{type:"raster-dem",tiles:["https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png"],tileSize:256,encoding:"terrarium"}},layers:[{id:"osm",type:"raster",source:"osm"}],terrain:{source:"terrain",exaggeration}}}); map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"top-right"); map.on("load",()=>{masks.forEach((m,i)=>{map.addSource(m.id,{type:"geojson",data:m.url}); map.addLayer({id:`${m.id}-fill`,type:"fill",source:m.id,paint:{"fill-color":["interpolate",["linear"],["zoom"],4,"#ef4444",9,"#f97316"],"fill-opacity":0.24}}); map.addLayer({id:`${m.id}-line`,type:"line",source:m.id,paint:{"line-color":"#fecaca","line-width":2,"line-dasharray":[2,2]}});}); setStatus("Terreno 3D y máscaras cargados");}); mapRef.current=map; return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return; for(const m of masks){for(const suffix of ["fill","line"]){const id=`${m.id}-${suffix}`;if(map.getLayer(id))map.setLayoutProperty(id,"visibility",visible[m.id]?"visible":"none")}}},[visible]);
 useEffect(()=>{const map=mapRef.current;if(map?.getSource("terrain"))map.setTerrain({source:"terrain",exaggeration})},[exaggeration]);
 return <main className="min-h-screen bg-slate-950 text-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700 bg-slate-900 p-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-300">A3 · VISOR GEOESPACIAL</p><h1 className="text-2xl font-bold">Mapa 3D y máscaras de radar</h1><p className="text-sm text-slate-300">Vista tridimensional del relieve con superposición de las coberturas S-300. La máscara permite apreciar bloqueos y sombras del terreno de forma visual.</p></div><div className="flex flex-wrap gap-2"><Link href={`/espacio/${workspaceCode}/${token}`} className="rounded bg-slate-700 px-3 py-2">Mapa 2D</Link><Link href={`/espacio/${workspaceCode}/${token}/ppc/pcr`} className="rounded bg-violet-700 px-3 py-2">PCR</Link><Link href={`/espacio/${workspaceCode}/${token}/ppc/computo-aereo`} className="rounded bg-cyan-700 px-3 py-2">Cómputo Aéreo</Link></div></header><div className="grid min-h-[calc(100vh-100px)] lg:grid-cols-[310px_1fr]"><aside className="border-r border-slate-700 bg-slate-900 p-4"><p className="mb-4 rounded border border-emerald-800 bg-emerald-950/40 p-2 text-sm text-emerald-200">{status}</p><h2 className="mb-2 font-bold">Coberturas visibles</h2>{masks.map(m=><label key={m.id} className="mb-2 flex items-center gap-2 rounded border border-slate-700 p-2"><input type="checkbox" checked={visible[m.id]} onChange={e=>setVisible(v=>({...v,[m.id]:e.target.checked}))}/><span>{m.name}</span></label>)}<label className="mt-5 block text-sm font-bold">Exageración vertical: {exaggeration.toFixed(1)}×<input type="range" min="1" max="3" step="0.1" value={exaggeration} onChange={e=>setExaggeration(Number(e.target.value))} className="mt-2 w-full"/></label><div className="mt-5 rounded border border-amber-800 bg-amber-950/30 p-3 text-xs text-amber-100"><strong>Interpretación:</strong> incline y rote el mapa para observar cómo las elevaciones cortan visualmente las máscaras. Esta vista es de apoyo al planeamiento; el cálculo exacto de línea de vista requiere perfiles de elevación por azimut y altura del blanco.</div></aside><div ref={ref} className="min-h-[720px] w-full"/></div></main>
}
