"use client";

import { useEffect, useRef, useState } from "react";

type Axis = "x" | "y" | "z";
type Vec3 = [number, number, number];
type Mat4 = Float32Array;
type GltfAccessor = { bufferView?:number; byteOffset?:number; componentType:number; count:number; type:string; min?:number[]; max?:number[] };
type GltfBufferView = { buffer:number; byteOffset?:number; byteLength:number; byteStride?:number; target?:number };
type GltfPrimitive = { attributes:Record<string,number>; indices?:number; material?:number; mode?:number };
type GltfMesh = { primitives:GltfPrimitive[] };
type GltfNode = { mesh?:number; children?:number[]; matrix?:number[]; translation?:number[]; rotation?:number[]; scale?:number[] };
type GltfMaterial = { alphaMode?:string; doubleSided?:boolean; pbrMetallicRoughness?:{baseColorFactor?:number[];baseColorTexture?:{index:number};metallicFactor?:number;roughnessFactor?:number} };
type Gltf = { scene?:number; scenes:{nodes?:number[]}[]; buffers:{uri:string;byteLength:number}[]; bufferViews:GltfBufferView[]; accessors:GltfAccessor[]; meshes:GltfMesh[]; nodes:GltfNode[]; materials?:GltfMaterial[]; textures?:{source:number}[]; images?:{uri:string}[] };
type DrawItem={primitive:GltfPrimitive;nodeWorld:Mat4;material:GltfMaterial|undefined;transparent:boolean};
type Runtime={gltf:Gltf;viewBuffers:WebGLBuffer[];textures:(WebGLTexture|null)[];drawItems:DrawItem[];center:Vec3;fitScale:number};

type Props={
  title:string; subtitle:string; modelRoot:string;
  background:"hangar"|"ocean"; useTextures?:boolean; targetSize?:number;
  initial?:{x:number;y:number;z:number};
};

function identity():Mat4{return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}
function multiply(a:Mat4,b:Mat4):Mat4{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function translation(x:number,y:number,z:number):Mat4{const m=identity();m[12]=x;m[13]=y;m[14]=z;return m}
function scaleMat(x:number,y:number,z:number):Mat4{const m=identity();m[0]=x;m[5]=y;m[10]=z;return m}
function rotX(a:number):Mat4{const c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1])}
function rotY(a:number):Mat4{const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1])}
function rotZ(a:number):Mat4{const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,s,0,0,-s,c,0,0,0,1,0,0,0,0,0,1])}
function perspective(fov:number,aspect:number,near:number,far:number):Mat4{const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0])}
function quaternionMat(q:number[]):Mat4{const[x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([1-(yy+zz),xy+wz,xz-wy,0,xy-wz,1-(xx+zz),yz+wx,0,xz+wy,yz-wx,1-(xx+yy),0,0,0,0,1])}
function nodeMatrix(n:GltfNode):Mat4{if(n.matrix)return new Float32Array(n.matrix);let m=identity();if(n.translation)m=multiply(m,translation(...n.translation as [number,number,number]));if(n.rotation)m=multiply(m,quaternionMat(n.rotation));if(n.scale)m=multiply(m,scaleMat(...n.scale as [number,number,number]));return m}
function transformPoint(m:Mat4,p:Vec3):Vec3{const[x,y,z]=p,w=m[3]*x+m[7]*y+m[11]*z+m[15]||1;return[(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w]}
function compile(gl:WebGL2RenderingContext,type:number,src:string){const s=gl.createShader(type);if(!s)throw new Error("Shader");gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||"Shader");return s}
function program(gl:WebGL2RenderingContext,vs:string,fs:string){const p=gl.createProgram();if(!p)throw new Error("Programa");gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||"Programa");return p}
function numComponents(t:string){return t==="SCALAR"?1:t==="VEC2"?2:t==="VEC3"?3:t==="VEC4"?4:1}
function glType(gl:WebGL2RenderingContext,t:number){return t===5120?gl.BYTE:t===5121?gl.UNSIGNED_BYTE:t===5122?gl.SHORT:t===5123?gl.UNSIGNED_SHORT:t===5125?gl.UNSIGNED_INT:gl.FLOAT}
async function loadTexture(gl:WebGL2RenderingContext,url:string){const img=new Image();img.crossOrigin="anonymous";img.src=url;await img.decode();const tex=gl.createTexture();if(!tex)return null;gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,1);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);return tex}
async function loadRuntime(gl:WebGL2RenderingContext,root:string,targetSize:number,useTextures:boolean):Promise<Runtime>{
 const gltf=await fetch(`${root}scene.gltf`).then(r=>{if(!r.ok)throw new Error("No se pudo cargar scene.gltf");return r.json()}) as Gltf;
 const binary=await fetch(`${root}${gltf.buffers[0].uri}`).then(r=>r.arrayBuffer());
 const viewBuffers=gltf.bufferViews.map(bv=>{const b=gl.createBuffer();if(!b)throw new Error("Buffer");const target=bv.target===34963?gl.ELEMENT_ARRAY_BUFFER:gl.ARRAY_BUFFER;gl.bindBuffer(target,b);gl.bufferData(target,new Uint8Array(binary,bv.byteOffset||0,bv.byteLength),gl.STATIC_DRAW);return b});
 const textures:(WebGLTexture|null)[]=[]; if(useTextures)for(const image of gltf.images||[])textures.push(await loadTexture(gl,`${root}${image.uri}`));
 const drawItems:DrawItem[]=[];const world:Mat4[]=gltf.nodes.map(()=>identity());const roots=gltf.scenes[gltf.scene||0]?.nodes||[];
 const walk=(idx:number,parent:Mat4)=>{const n=gltf.nodes[idx],w=multiply(parent,nodeMatrix(n));world[idx]=w;if(n.mesh!==undefined)for(const primitive of gltf.meshes[n.mesh].primitives){const material=gltf.materials?.[primitive.material??-1];drawItems.push({primitive,nodeWorld:w,material,transparent:material?.alphaMode==="BLEND"})}for(const c of n.children||[])walk(c,w)};roots.forEach(r=>walk(r,identity()));
 const min:Vec3=[Infinity,Infinity,Infinity],max:Vec3=[-Infinity,-Infinity,-Infinity];gltf.nodes.forEach((n,idx)=>{if(n.mesh===undefined)return;for(const prim of gltf.meshes[n.mesh].primitives){const a=gltf.accessors[prim.attributes.POSITION];if(!a?.min||!a?.max)continue;for(const x of[a.min[0],a.max[0]])for(const y of[a.min[1],a.max[1]])for(const z of[a.min[2],a.max[2]]){const p=transformPoint(world[idx],[x,y,z]);for(let k=0;k<3;k++){min[k]=Math.min(min[k],p[k]);max[k]=Math.max(max[k],p[k])}}}});
 const center:Vec3=[(min[0]+max[0])/2,(min[1]+max[1])/2,(min[2]+max[2])/2],maxDim=Math.max(max[0]-min[0],max[1]-min[1],max[2]-min[2]);return{gltf,viewBuffers,textures,drawItems,center,fitScale:targetSize/Math.max(maxDim,.001)};
}
const vs=`#version 300 es\nprecision highp float;in vec3 aPosition;in vec3 aNormal;in vec2 aUv;uniform mat4 uMvp;uniform mat4 uModel;out vec3 vNormal;out vec2 vUv;out vec3 vWorld;void main(){vec4 w=uModel*vec4(aPosition,1.0);vWorld=w.xyz;vNormal=normalize(mat3(uModel)*aNormal);vUv=aUv;gl_Position=uMvp*vec4(aPosition,1.0);}`;
const fs=`#version 300 es\nprecision highp float;in vec3 vNormal;in vec2 vUv;in vec3 vWorld;out vec4 outColor;uniform sampler2D uBaseTex;uniform bool uHasTex;uniform vec4 uBaseColor;uniform float uMetallic;uniform float uRoughness;void main(){vec4 base=uBaseColor;if(uHasTex)base*=texture(uBaseTex,vUv);if(base.a<.03)discard;vec3 n=normalize(vNormal),l=normalize(vec3(-.45,.72,.58)),v=normalize(vec3(0.,0.,4.5)-vWorld),h=normalize(l+v);float diff=max(dot(n,l),0.),spec=pow(max(dot(n,h),0.),mix(68.,10.,uRoughness))*mix(.16,.55,uMetallic),rim=pow(1.-max(dot(n,v),0.),2.);vec3 col=base.rgb*(.48+.92*diff)+vec3(spec)+base.rgb*rim*.14;outColor=vec4(col,base.a);}`;

export default function GenericModelViewer({title,subtitle,modelRoot,background,useTextures=true,targetSize=4.25,initial={x:-.18,y:.55,z:0}}:Props){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),boxRef=useRef<HTMLDivElement|null>(null),runtimeRef=useRef<Runtime|null>(null),rotation=useRef({...initial}),zoom=useRef(1),pan=useRef({x:0,y:0}),drag=useRef<{x:number;y:number}|null>(null);
 const[auto,setAuto]=useState(true),[axis,setAxis]=useState<Axis>("y"),[speed,setSpeed]=useState(.22),[move,setMove]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[fullscreen,setFullscreen]=useState(false);
 useEffect(()=>{const f=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener("fullscreenchange",f);return()=>document.removeEventListener("fullscreenchange",f)},[]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const gl=canvas.getContext("webgl2",{antialias:true,alpha:true});if(!gl){setError("WebGL2 no disponible");setLoading(false);return}let cancelled=false,raf=0,last=performance.now();const p=program(gl,vs,fs),loc={pos:gl.getAttribLocation(p,"aPosition"),normal:gl.getAttribLocation(p,"aNormal"),uv:gl.getAttribLocation(p,"aUv"),mvp:gl.getUniformLocation(p,"uMvp"),model:gl.getUniformLocation(p,"uModel"),hasTex:gl.getUniformLocation(p,"uHasTex"),baseTex:gl.getUniformLocation(p,"uBaseTex"),baseColor:gl.getUniformLocation(p,"uBaseColor"),metallic:gl.getUniformLocation(p,"uMetallic"),roughness:gl.getUniformLocation(p,"uRoughness")};gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);loadRuntime(gl,modelRoot,targetSize,useTextures).then(rt=>{if(!cancelled){runtimeRef.current=rt;setLoading(false)}}).catch(e=>{if(!cancelled){setError(String(e));setLoading(false)}});
 const bind=(rt:Runtime,ai:number,location:number)=>{if(location<0)return;const a=rt.gltf.accessors[ai];if(a.bufferView===undefined)return;const bv=rt.gltf.bufferViews[a.bufferView];gl.bindBuffer(gl.ARRAY_BUFFER,rt.viewBuffers[a.bufferView]);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,numComponents(a.type),glType(gl,a.componentType),false,bv.byteStride||0,a.byteOffset||0)};
 const draw=(now:number)=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2),w=Math.max(2,Math.floor(rect.width*dpr)),h=Math.max(2,Math.floor(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const rt=runtimeRef.current;if(rt){const dt=Math.min((now-last)/1000,.05);last=now;if(auto)rotation.current[axis]+=dt*speed;const proj=perspective(Math.PI/4,w/h,.05,80),view=translation(pan.current.x,pan.current.y,-4.1/zoom.current),base=multiply(rotZ(rotation.current.z),multiply(rotX(rotation.current.x),rotY(rotation.current.y)));let global=multiply(base,scaleMat(rt.fitScale,rt.fitScale,rt.fitScale));global=multiply(global,translation(-rt.center[0],-rt.center[1],-rt.center[2]));gl.useProgram(p);gl.uniform1i(loc.baseTex,0);for(const transparent of[false,true]){if(transparent){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false)}else{gl.disable(gl.BLEND);gl.depthMask(true)}for(const item of rt.drawItems){if(item.transparent!==transparent)continue;const prim=item.primitive,model=multiply(global,item.nodeWorld),mvp=multiply(proj,multiply(view,model));gl.uniformMatrix4fv(loc.model,false,model);gl.uniformMatrix4fv(loc.mvp,false,mvp);bind(rt,prim.attributes.POSITION,loc.pos);if(prim.attributes.NORMAL!==undefined)bind(rt,prim.attributes.NORMAL,loc.normal);if(prim.attributes.TEXCOORD_0!==undefined)bind(rt,prim.attributes.TEXCOORD_0,loc.uv);const mat=item.material?.pbrMetallicRoughness,color=mat?.baseColorFactor||[.55,.62,.68,1];gl.uniform4f(loc.baseColor,color[0]??.55,color[1]??.62,color[2]??.68,color[3]??1);gl.uniform1f(loc.metallic,mat?.metallicFactor??.25);gl.uniform1f(loc.roughness,mat?.roughnessFactor??.55);const ti=mat?.baseColorTexture?.index,source=useTextures&&ti!==undefined?rt.gltf.textures?.[ti]?.source:undefined,tex=source!==undefined?rt.textures[source]:null;gl.uniform1i(loc.hasTex,tex?1:0);if(tex){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex)}if(item.material?.doubleSided)gl.disable(gl.CULL_FACE);else gl.enable(gl.CULL_FACE);if(prim.indices!==undefined){const ia=rt.gltf.accessors[prim.indices];gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,rt.viewBuffers[ia.bufferView!]);gl.drawElements(prim.mode??gl.TRIANGLES,ia.count,glType(gl,ia.componentType),ia.byteOffset||0)}else gl.drawArrays(prim.mode??gl.TRIANGLES,0,rt.gltf.accessors[prim.attributes.POSITION].count)}}gl.depthMask(true)}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{cancelled=true;cancelAnimationFrame(raf);gl.deleteProgram(p)}},[auto,axis,speed,modelRoot,targetSize,useTextures]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const wheel=(e:WheelEvent)=>{e.preventDefault();e.stopPropagation();zoom.current=Math.max(.5,Math.min(3,zoom.current*(e.deltaY>0?.92:1.08)))};c.addEventListener("wheel",wheel,{passive:false});return()=>c.removeEventListener("wheel",wheel)},[]);
 const reset=()=>{rotation.current={...initial};zoom.current=1;pan.current={x:0,y:0};setMove(false)};const full=async()=>{if(!boxRef.current)return;if(!document.fullscreenElement)await boxRef.current.requestFullscreen();else await document.exitFullscreen()};
 const bg=background==="hangar"?"linear-gradient(rgba(2,6,23,.08),rgba(2,6,23,.22)),url('/images/medios3d/hangar-ficticio-v23.jpg')":"radial-gradient(circle at 50% 20%,rgba(125,211,252,.25),transparent 35%),linear-gradient(to bottom,#16334b 0%,#245774 48%,#0b2639 49%,#061726 100%)";
 return <div ref={boxRef} className={`relative flex min-h-[760px] flex-col overflow-hidden rounded-2xl border border-cyan-300/20 bg-slate-950 shadow-2xl ${fullscreen?"h-screen rounded-none border-0":""}`}>
  <div className="flex flex-wrap items-center gap-2 border-b border-white/10 bg-slate-950/95 p-3 text-xs"><button onClick={()=>setAuto(v=>!v)} className={`rounded-lg border px-3 py-2 font-bold ${auto?"border-emerald-400/60 bg-emerald-400/10 text-emerald-200":"border-white/15 text-slate-300"}`}>{auto?"Auto rotación":"Rotación manual"}</button><select value={axis} onChange={e=>setAxis(e.target.value as Axis)} className="rounded-lg border border-white/15 bg-slate-900 px-2 py-2"><option value="x">Eje X</option><option value="y">Eje Y</option><option value="z">Eje Z</option></select><label className="flex items-center gap-2 text-slate-300">Velocidad <input type="range" min=".03" max="1.5" step=".03" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label><button onClick={()=>setMove(v=>!v)} className={`rounded-lg border px-3 py-2 font-bold ${move?"border-cyan-300/60 bg-cyan-300/10":"border-white/15"}`}>{move?"Moviendo medio":"Mover / centrar"}</button><button onClick={()=>{pan.current={x:0,y:0};setMove(false)}} className="rounded-lg border border-white/15 px-3 py-2 font-bold">Centrar</button><button onClick={reset} className="rounded-lg border border-white/15 px-3 py-2 font-bold">Reset cámara</button><button onClick={full} className="ml-auto rounded-lg border border-cyan-300/30 px-3 py-2 font-bold text-cyan-100">{fullscreen?"Salir pantalla completa":"Pantalla completa"}</button></div>
  <div className="flex gap-2 border-b border-white/10 bg-slate-950/80 px-3 py-2 text-[11px] font-bold uppercase"><button onClick={()=>rotation.current={...initial}} className="rounded px-2 py-1 text-cyan-200">Perspectiva</button><button onClick={()=>rotation.current={x:0,y:0,z:0}} className="rounded px-2 py-1">Lateral</button><button onClick={()=>rotation.current={x:0,y:Math.PI/2,z:0}} className="rounded px-2 py-1">Frontal</button><button onClick={()=>rotation.current={x:-Math.PI/2,y:0,z:0}} className="rounded px-2 py-1">Superior</button><span className="ml-auto hidden normal-case text-slate-400 lg:inline">Arrastrar: rotar · Mover/centrar: desplazar · Shift: eje Z · rueda: zoom</span></div>
  <div className="relative min-h-[670px] flex-1 overflow-hidden bg-cover bg-center" style={{backgroundImage:bg,backgroundRepeat:"no-repeat",backgroundSize:"cover"}}><canvas ref={canvasRef} className="absolute inset-0 h-full w-full touch-none" onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y;drag.current={x:e.clientX,y:e.clientY};if(move){pan.current.x=Math.max(-1.8,Math.min(1.8,pan.current.x+dx*.0045));pan.current.y=Math.max(-1.2,Math.min(1.2,pan.current.y-dy*.0045))}else if(e.shiftKey)rotation.current.z+=dx*.008;else{rotation.current.y+=dx*.008;rotation.current.x+=dy*.008}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}/><div className="pointer-events-none absolute left-4 top-4 rounded-lg border border-cyan-300/20 bg-slate-950/75 px-3 py-2 backdrop-blur"><p className="text-[10px] font-black uppercase tracking-[.22em] text-cyan-300">{title}</p><p className="mt-1 text-[10px] text-slate-300">{subtitle}</p><p className="mt-1 max-w-[420px] text-[9px] uppercase tracking-[.14em] text-slate-500">Modelo 3D de referencia para ZEUS</p></div>{!useTextures&&<div className="pointer-events-none absolute right-4 top-4 rounded-lg border border-amber-300/25 bg-slate-950/75 px-3 py-2 text-[9px] font-black uppercase tracking-[.16em] text-amber-200">Render neutro · sin identificación nacional</div>}{loading&&<div className="absolute inset-0 flex items-center justify-center bg-slate-950/55"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">Cargando modelo 3D…</p></div>}{error&&<div className="absolute inset-0 flex items-center justify-center bg-slate-950/90 p-6 text-red-200">{error}</div>}</div>
 </div>
}
